# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='int32_math',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\nint32_math\"#\n\x12\x43\x61lculationRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"$\n\x13\x43\x61lculationResponse\x12\r\n\x05value\x18\x01 \x01(\x05\x32\xdf\x02\n\nCalculator\x12K\n\x06Square\x12\x1e.int32_math.CalculationRequest\x1a\x1f.int32_math.CalculationResponse\"\x00\x12]\n\x16NaturalNumberGenerator\x12\x1e.int32_math.CalculationRequest\x1a\x1f.int32_math.CalculationResponse\"\x00\x30\x01\x12P\n\tSummation\x12\x1e.int32_math.CalculationRequest\x1a\x1f.int32_math.CalculationResponse\"\x00(\x01\x12S\n\nBuffer3Sum\x12\x1e.int32_math.CalculationRequest\x1a\x1f.int32_math.CalculationResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_CALCULATIONREQUEST = _descriptor.Descriptor(
  name='CalculationRequest',
  full_name='int32_math.CalculationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='int32_math.CalculationRequest.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=67,
)


_CALCULATIONRESPONSE = _descriptor.Descriptor(
  name='CalculationResponse',
  full_name='int32_math.CalculationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='int32_math.CalculationResponse.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['CalculationRequest'] = _CALCULATIONREQUEST
DESCRIPTOR.message_types_by_name['CalculationResponse'] = _CALCULATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculationRequest = _reflection.GeneratedProtocolMessageType('CalculationRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATIONREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:int32_math.CalculationRequest)
  ))
_sym_db.RegisterMessage(CalculationRequest)

CalculationResponse = _reflection.GeneratedProtocolMessageType('CalculationResponse', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATIONRESPONSE,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:int32_math.CalculationResponse)
  ))
_sym_db.RegisterMessage(CalculationResponse)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='int32_math.Calculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=108,
  serialized_end=459,
  methods=[
  _descriptor.MethodDescriptor(
    name='Square',
    full_name='int32_math.Calculator.Square',
    index=0,
    containing_service=None,
    input_type=_CALCULATIONREQUEST,
    output_type=_CALCULATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NaturalNumberGenerator',
    full_name='int32_math.Calculator.NaturalNumberGenerator',
    index=1,
    containing_service=None,
    input_type=_CALCULATIONREQUEST,
    output_type=_CALCULATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Summation',
    full_name='int32_math.Calculator.Summation',
    index=2,
    containing_service=None,
    input_type=_CALCULATIONREQUEST,
    output_type=_CALCULATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Buffer3Sum',
    full_name='int32_math.Calculator.Buffer3Sum',
    index=3,
    containing_service=None,
    input_type=_CALCULATIONREQUEST,
    output_type=_CALCULATIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
